apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "5 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-task
            image: shrikantk7/etl_task
            args:
            - /app/main.py
          restartPolicy: OnFailure