apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "50 9  * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl-task
            image: ankit9911/etl:latest
            args:
            - /app/main.py
          restartPolicy: OnFailure