apiVersion: apps/v1
kind: Deployment
metadata:
  name: etl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etl
  template:
    metadata:
      labels:
        app: etl
    spec:
      containers:
      - name: etl-container
        image: ankit9911/etl:latest
        ports:
        - containerPort: 8080
        env:
        - name: LOGSTASH_HOST
          value: "172.29.170.199"
        - name: LOGSTASH_PORT
          value: "5000"
