apiVersion: v1
kind: Service
metadata:
  name: etl-service
spec:
  selector:
    app: etl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30070
  type: LoadBalancer
