name: ETL Pipeline CI/CD

on:
  push:
    branches:
      - ankit
  schedule:
    - cron: '0 0 * * *'  # Schedule it to run daily at midnight

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: 3.11.6

    # - name: Send Logs to Logstash
    #   run: |
    #    # Checkout the 'ankit' branch of the repository
    #     git checkout ankit

    #    # Copy Logstash configuration from the 'ankit' branch to the current working directory
    #     cp -n etl_logstash.conf .

    #    # Send a POST request to Logstash with the Logstash configuration
    #     curl -X POST -H 'Content-Type: application/json' -d @etl_logstash.conf http://localhost:5044

    # - name: Install Dependencies
    #   run: |
    #     pip install --upgrade pip
    #     pip install -r requirements.txt

    # - name: Run Tests with Bandit
    #   run: |
    #     pip install bandit
    #     bandit -r .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build -t ankit9911/etl:latest .
 
    - name: Push the Docker image
      run: docker push ankit9911/etl:latest

    - name: Save Logs as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: github_actions_logs

    - name: Ship Logs to Logstash
      uses: actions/ship-logs-to-logstash@v1
      with:
      logstash-host: 4fb7-116-73-143-230.ngrok-free.app
      logstash-port: 5044

        path: ${{ github.workspace }}/.github/workflows

