name: ETL Pipeline CI/CD

on:
  push:
    branches:
      - main 
  schedule:
    - cron: '0 0 * * *'  # Schedule it to run daily at midnight

jobs:  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Run Tests with Bandit
      run: |
        pip install bandit
        bandit -r . -s B113

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build the Docker image
      run: docker build --build-arg OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }} --build-arg IRCTC_API_KEY=${{ secrets.IRCTC_API_KEY }} --build-arg IRCTC_API_HOST=${{ secrets.IRCTC_API_HOST }} --build-arg MYSQL_HOST=${{ secrets.MYSQL_HOST }} --build-arg MYSQL_USER=${{ secrets.MYSQL_USER }} --build-arg MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} --build-arg MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} -t ankit9911/etl:latest .
 
    - name: Push the Docker image
      run: docker push ankit9911/etl:latest
